/** Canon editorial del expediente #004. */
import { caseAssets, type CaseDefinition } from './definition.ts';

const art = caseAssets('noventa-segundos-de-sombra');

const clue = (
  id:string,name:string,kind:CaseDefinition['clues'][number]['kind'],foundAt:string,
  found:string,analyzed:string,
): CaseDefinition['clues'][number] => ({
  id:'c004-cl-'+id,name,kind,foundAt,imagePublicId:art.clue(id),
  states:[
    {key:'found',label:name,description:found},
    {key:'analyzed',label:name+' — analizada',description:analyzed},
  ],
});

export const case004: CaseDefinition = {
  id:'c004',slug:'noventa-segundos-de-sombra',fileCode:'#004',
  title:'Noventa segundos de sombra',subtitle:'Desaparición en un radiotelescopio',
  place:'Sierra de los Filabres, Almería',dateLabel:'Madrugada del 24 de julio de 1977',
  victimName:'Dra. Elisa Montalbán',
  briefing:'A las 00:10, un apagón de exactamente noventa segundos dejó a oscuras el radiotelescopio experimental. Al volver la corriente, la directora del proyecto había desaparecido, una mancha oscura marcaba la barandilla sobre el barranco y la cinta maestra de una supuesta señal astronómica ya no estaba en su armario. La tormenta ha cortado la carretera: nadie ha podido abandonar la cumbre.',
  coverPublicId:art.cover,entryNodeId:'c004-n-intro',
  suspects:[
    {id:'c004-s-elisa',name:'Elisa Montalbán',role:'Directora científica',portraitPublicId:art.suspect('elisa-montalban'),description:'Cuarenta y seis años. Cabello negro con una franja blanca, jersey color óxido y una cicatriz junto a la ceja. Desde el apagón nadie la ha visto.',relation:'Dirige el proyecto Asterión y custodiaba la cinta original.',facts:[
      {id:'c004-f-elisa-desaparecida',kind:'testimony',headline:'Desapareció durante el apagón',detail:'Su silla quedó volcada y una mancha oscura hizo pensar en una caída.'},
      {id:'c004-f-elisa-tunel',kind:'contradiction',headline:'Conocía el paso de cables',detail:'Supervisó el sellado del conducto entre la antena y el cuarto fotográfico.'},
      {id:'c004-f-elisa-cinta',kind:'contradiction',headline:'Conservaba la cinta desaparecida',detail:'Al ser encontrada lleva el carrete maestro dentro de una bolsa.'},
      {id:'c004-f-elisa-presion',kind:'motive',headline:'Debía demostrar el hallazgo al amanecer',detail:'Madrid exigía la cinta antes de renovar la dirección y la financiación.'},
    ]},
    {id:'c004-s-ines',name:'Inés Valcárcel',role:'Ingeniera electrónica',portraitPublicId:art.suspect('ines-valcarcel'),description:'Treinta y ocho años. Pelo rizado muy corto, camisa mostaza y gafas cuadradas. Responde con cifras.',relation:'Diseñó el receptor y el relé de protección.',facts:[
      {id:'c004-f-ines-alibi',kind:'alibi',headline:'Permaneció en la consola auxiliar',detail:'El papel conserva sus ajustes cada diez segundos durante todo el corte.'},
      {id:'c004-f-ines-oferta',kind:'motive',headline:'Había aceptado otro empleo',detail:'Ocultaba una oferta de Bonn y una disputa por la autoría del receptor.'},
      {id:'c004-f-ines-pulso',kind:'testimony',headline:'Reconoce la calibración',detail:'La cadencia coincide con el generador local usado al comenzar cada turno.'},
      {id:'c004-f-ines-llave',kind:'contradiction',headline:'Duplicó una llave',detail:'Copió la llave del armario de cintas para trabajar de madrugada.'},
    ]},
    {id:'c004-s-soraya',name:'Soraya Núñez',role:'Operadora nocturna',portraitPublicId:art.suspect('soraya-nunez'),description:'Veintinueve años. Melena oscura, chaleco azul y auriculares al cuello. Anota con tinta violeta.',relation:'Controlaba la antena y firmó el diario de observación.',facts:[
      {id:'c004-f-soraya-alibi',kind:'alibi',headline:'Quedó registrada al teléfono',detail:'La centralita conservó su llamada entre las 00:08 y las 00:14.'},
      {id:'c004-f-soraya-llamada',kind:'contradiction',headline:'Ocultó una llamada personal',detail:'Usó la línea científica y falseó su duración.'},
      {id:'c004-f-soraya-diario',kind:'testimony',headline:'Copió una hora dictada',detail:'Elisa dictó la hora de Asterión en vez de usar el reloj sidéreo.'},
    ]},
    {id:'c004-s-teresa',name:'Teresa Acedo',role:'Fotoperiodista',portraitPublicId:art.suspect('teresa-acedo'),description:'Cincuenta y dos años. Cabello canoso recogido, chaqueta granate y una Leica al pecho.',relation:'La única visitante; había discutido con Elisa por unas fotos embargadas.',facts:[
      {id:'c004-f-teresa-alibi',kind:'alibi',headline:'Fotografió el cielo durante el corte',detail:'Una exposición mantiene su cámara fija de 00:09:42 a 00:12:18.'},
      {id:'c004-f-teresa-negativo',kind:'contradiction',headline:'Escondió un negativo prohibido',detail:'Fotografió el presupuesto y escondió la película en su bolsa.'},
      {id:'c004-f-teresa-mancha',kind:'testimony',headline:'Reconoce el revelador',detail:'La mancha huele al concentrado que faltaba del cuarto fotográfico.'},
    ]},
    {id:'c004-s-gabriel',name:'Gabriel Requena',role:'Encargado de mantenimiento',portraitPublicId:art.suspect('gabriel-requena'),description:'Sesenta años. Barba gris, mono verde y manos ennegrecidas por grasa.',relation:'Mantiene el generador, los accesos y la antena.',facts:[
      {id:'c004-f-gabriel-alibi',kind:'alibi',headline:'Estaba en la caseta meteorológica',detail:'Firmó lecturas a las 00:09, 00:11 y 00:13, a cuatro minutos de la antena.'},
      {id:'c004-f-gabriel-gasoil',kind:'contradiction',headline:'Desviaba combustible',detail:'El libro oculta cuarenta litros vendidos a un pastor.'},
      {id:'c004-f-gabriel-tunel',kind:'testimony',headline:'El conducto seguía abierto',detail:'Sólo taparon los extremos; detrás del armario quedó una entrada.'},
    ]},
  ],
  clues:[
    clue('registro-consola','Registro continuo de la consola','context','Sala de control','El papel avanzó durante el corte.','Los ajustes cada diez segundos sitúan a Inés ante la consola.'),
    clue('diario-observacion','Diario de observación','essential','Sala de control','La hora de Asterión está escrita a mano.','Elisa dictó las 23:47; falta la marca del reloj sidéreo.'),
    clue('oscilograma','Oscilograma de Asterión','essential','Sala de control','Los pulsos son extraordinariamente regulares.','Coinciden con el generador local y carecen de deriva celeste.'),
    clue('rele-proteccion','Relé de protección','essential','Cuarto eléctrico','La tapa tiene un arañazo reciente.','Un puente lo conectó a un temporizador durante noventa segundos.'),
    clue('temporizador','Temporizador de ampliadora','essential','Cuarto fotográfico','El dial está fijado en 90.','Sus bornes conservan el mismo cobre que el puente del relé.'),
    clue('mancha-barandilla','Mancha de la barandilla','essential','Terraza occidental','La salpicadura baja hacia el barranco.','Es revelador con óxido, no sangre.'),
    clue('huellas-polvo','Huellas en polvo rojo','essential','Base de la antena','El rastro entra bajo un panel.','La bota derecha sin tacón caminó hacia el conducto.'),
    clue('plano-conductos','Plano de conductos de 1968','essential','Archivo técnico','Un trazado une antena y cuarto fotográfico.','El paso de 92 cm termina detrás del armario de placas.'),
    clue('telegrama','Telegrama de Madrid','essential','Despacho de Elisa','El comité pide material sin procesar.','Sin la cinta, Elisa perdería dirección y financiación.'),
    clue('copia-cinta','Copia de trabajo de Asterión','essential','Armario de cintas','La bobina secundaria conserva la señal.','La señal fue empalmada desde una calibración anterior.'),
    clue('cinta-maestra','Cinta maestra desaparecida','essential','Cuarto fotográfico','El carrete aparece en la bolsa de Elisa.','La zona de las 23:47 fue desmagnetizada; no hay señal.'),
    clue('larga-exposicion','Fotografía de larga exposición','context','Terraza oriental','La cámara siguió abierta durante el corte.','Los arcos estelares fijan a Teresa junto al trípode.'),
    clue('cinta-centralita','Cinta de la centralita','context','Sala de comunicaciones','Una llamada atravesó el apagón.','La voz de Soraya consta entre 00:08 y 00:14.'),
    clue('pluviografo','Banda del pluviógrafo','context','Caseta meteorológica','Tres lecturas rodean el corte.','Gabriel firmó a las 00:09, 00:11 y 00:13.'),
    clue('libro-gasoil','Libro del generador','red_herring','Cuarto eléctrico','El consumo no coincide con el depósito.','Faltan cuarenta litros, pero el generador arrancó bien.'),
    clue('negativo-presupuesto','Negativo presupuestario','red_herring','Bolsa de Teresa','Muestra una página reservada.','Teresa investigaba gastos irregulares ajenos al apagón.'),
  ],
  nodes:[
    {id:'c004-n-intro',kind:'intro',title:'La sombra sobre la antena',location:'Radiotelescopio experimental',body:'La corriente vuelve con un golpe seco. El gran plato queda inmóvil contra los relámpagos y el reloj marca las 00:12.\n\nLa silla de Elisa está volcada. Una mancha conduce a la barandilla sobre el barranco. Inés encuentra vacío el hueco de la cinta maestra.\n\nLa carretera está cortada. Si Elisa cayó, hay que localizarla; si fingió su caída, sigue dentro.',imagePublicId:art.scene('antena-noche')},
    {id:'c004-n-control',kind:'scene',title:'Examinar la sala de control',location:'Edificio de la antena',body:'El registrador auxiliar siguió avanzando durante el corte. El diario atribuye a Asterión una señal a las 23:47, pero la hora está escrita a mano. El oscilograma grapado parece demasiado regular.',imagePublicId:art.scene('sala-control'),effects:[{effect:'discover_clue',target:'c004-cl-registro-consola'},{effect:'discover_clue',target:'c004-cl-diario-observacion'},{effect:'discover_clue',target:'c004-cl-oscilograma'}]},
    {id:'c004-n-terraza',kind:'scene',title:'Registrar las terrazas',location:'Exterior de la cúpula',body:'La mancha occidental huele a químicos; no hay piel ni tela en la barandilla. Al este, la cámara de Teresa sigue montada y su contador indica una exposición de más de dos minutos.',imagePublicId:art.scene('terraza'),effects:[{effect:'discover_clue',target:'c004-cl-mancha-barandilla'},{effect:'discover_clue',target:'c004-cl-larga-exposicion'}]},
    {id:'c004-n-antena',kind:'scene',title:'Inspeccionar la base de la antena',location:'Pedestal',body:'El polvo rojizo conserva dos huellas junto a un panel. El borde inferior está limpio: alguien lo abrió hace poco.',imagePublicId:art.scene('base-antena'),effects:[{effect:'discover_clue',target:'c004-cl-huellas-polvo'}]},
    {id:'c004-n-electrico',kind:'scene',title:'Revisar el cuarto eléctrico',location:'Galería de servicio',body:'El generador arrancó a las 00:11:30. La corriente se perdió antes, en el relé de la antena. Su tapa está arañada y el libro de combustible tiene cifras corregidas.',imagePublicId:art.scene('cuarto-electrico'),effects:[{effect:'discover_clue',target:'c004-cl-rele-proteccion'},{effect:'discover_clue',target:'c004-cl-libro-gasoil'}]},
    {id:'c004-n-archivo',kind:'scene',title:'Abrir el archivo técnico',location:'Edificio principal',body:'Un plano de 1968 muestra un conducto omitido en la reforma. Une el pedestal con el cuarto fotográfico y lleva las iniciales E. M.',imagePublicId:art.scene('archivo-tecnico'),effects:[{effect:'discover_clue',target:'c004-cl-plano-conductos'}]},
    {id:'c004-n-despacho',kind:'scene',title:'Examinar el despacho de Elisa',location:'Edificio principal',body:'El armario no está forzado. Quedan una copia de Asterión y un telegrama de Madrid. A una de las botas de Elisa le falta el tacón derecho.',imagePublicId:art.scene('despacho'),effects:[{effect:'discover_clue',target:'c004-cl-copia-cinta'},{effect:'discover_clue',target:'c004-cl-telegrama'}]},
    {id:'c004-n-comunicaciones',kind:'scene',title:'Comprobar comunicaciones y meteorología',location:'Anexo oriental',body:'La centralita guardó una llamada mediante su batería. El pluviógrafo de la caseta conserva tres comprobaciones alrededor de medianoche.',imagePublicId:art.scene('comunicaciones'),effects:[{effect:'discover_clue',target:'c004-cl-cinta-centralita'},{effect:'discover_clue',target:'c004-cl-pluviografo'}]},
    {id:'c004-n-ines',kind:'interrogation',title:'Interrogar a Inés Valcárcel',location:'Consola auxiliar',body:'Inés creyó que Asterión era una calibración. Durante el corte siguió ajustando a ciegas el receptor. Admite que copió una llave y aceptó una oferta en Bonn.',imagePublicId:art.scene('ines'),effects:[{effect:'reveal_fact',target:'c004-f-ines-pulso'},{effect:'reveal_fact',target:'c004-f-ines-llave'},{effect:'reveal_fact',target:'c004-f-ines-oferta'}]},
    {id:'c004-n-soraya',kind:'interrogation',title:'Interrogar a Soraya Núñez',location:'Sala de control',body:'Soraya anotó las 23:47 porque Elisa se la dictó. Niega haberse separado durante el corte, pero el teléfono sigue descolgado.',imagePublicId:art.scene('soraya'),effects:[{effect:'reveal_fact',target:'c004-f-soraya-diario'}]},
    {id:'c004-n-teresa',kind:'interrogation',title:'Interrogar a Teresa Acedo',location:'Terraza oriental',body:'Teresa preparó una exposición larga antes del corte y reconoce el olor del revelador. Se resiste a entregar su bolsa fotográfica.',imagePublicId:art.scene('teresa'),effects:[{effect:'reveal_fact',target:'c004-f-teresa-mancha'},{effect:'discover_clue',target:'c004-cl-negativo-presupuesto'}]},
    {id:'c004-n-gabriel',kind:'interrogation',title:'Interrogar a Gabriel Requena',location:'Galería de servicio',body:'Gabriel estaba tomando lecturas meteorológicas. Recuerda que el viejo conducto nunca se rellenó y que Elisa supervisó la reforma.',imagePublicId:art.scene('gabriel'),effects:[{effect:'reveal_fact',target:'c004-f-gabriel-tunel'},{effect:'reveal_fact',target:'c004-f-elisa-tunel'}]},
    {id:'c004-n-registro',kind:'analysis',title:'Interpretar el registro continuo',location:'Sala de control',body:'Los ajustes manuales aparecen cada diez segundos y coinciden con la presión de Inés. La secuencia no se interrumpe durante el apagón.',imagePublicId:art.scene('laboratorio'),effects:[{effect:'advance_clue',target:'c004-cl-registro-consola',value:'analyzed'},{effect:'reveal_fact',target:'c004-f-ines-alibi'}]},
    {id:'c004-n-diario',kind:'analysis',title:'Contrastar el diario con el reloj sidéreo',location:'Sala de control',body:'Todas las observaciones llevan una perforación automática menos Asterión. Soraya copió una hora dictada por Elisa.',imagePublicId:art.scene('laboratorio'),effects:[{effect:'advance_clue',target:'c004-cl-diario-observacion',value:'analyzed'}]},
    {id:'c004-n-oscilograma',kind:'analysis',title:'Medir los pulsos de Asterión',location:'Laboratorio electrónico',body:'El oscilograma coincide con la plantilla del generador local. Una fuente celeste habría cambiado de fase con la rotación terrestre.',imagePublicId:art.scene('laboratorio'),effects:[{effect:'advance_clue',target:'c004-cl-oscilograma',value:'analyzed'}]},
    {id:'c004-n-rele',kind:'analysis',title:'Desmontar el relé de protección',location:'Cuarto eléctrico',body:'Hay cobre recién cortado y dos bornes pulidos. El relé fue puenteado para abrirse y cerrarse por una orden externa.',imagePublicId:art.scene('laboratorio'),effects:[{effect:'advance_clue',target:'c004-cl-rele-proteccion',value:'analyzed'},{effect:'discover_clue',target:'c004-cl-temporizador'}]},
    {id:'c004-n-temporizador',kind:'analysis',title:'Comparar el temporizador fotográfico',location:'Cuarto fotográfico',body:'El dial quedó en 90 segundos. Sus bornes conservan el mismo cobre que el puente del relé.',imagePublicId:art.scene('cuarto-fotografico'),effects:[{effect:'advance_clue',target:'c004-cl-temporizador',value:'analyzed'}]},
    {id:'c004-n-mancha',kind:'analysis',title:'Analizar la mancha de la barandilla',location:'Cuarto fotográfico',body:'El reactivo para sangre es negativo. Teresa identifica revelador concentrado mezclado con óxido.',imagePublicId:art.scene('cuarto-fotografico'),effects:[{effect:'advance_clue',target:'c004-cl-mancha-barandilla',value:'analyzed'}]},
    {id:'c004-n-huellas',kind:'analysis',title:'Leer las huellas del pedestal',location:'Base de la antena',body:'Las punteras señalan al panel. La huella derecha carece de tacón y coincide con las botas del despacho de Elisa.',imagePublicId:art.scene('base-antena'),effects:[{effect:'advance_clue',target:'c004-cl-huellas-polvo',value:'analyzed'}]},
    {id:'c004-n-plano',kind:'analysis',title:'Reconstruir el conducto de 1968',location:'Archivo técnico',body:'El paso mide 92 centímetros y termina detrás del armario de placas. Las iniciales de Elisa prueban que conocía el trazado.',imagePublicId:art.scene('archivo-tecnico'),effects:[{effect:'advance_clue',target:'c004-cl-plano-conductos',value:'analyzed'}]},
    {id:'c004-n-telegrama',kind:'analysis',title:'Descifrar el ultimátum de Madrid',location:'Despacho de Elisa',body:'El comité detectó inconsistencias y exigía la grabación continua antes de las ocho. Sin ella, Elisa perdería el proyecto.',imagePublicId:art.scene('despacho'),effects:[{effect:'advance_clue',target:'c004-cl-telegrama',value:'analyzed'},{effect:'reveal_fact',target:'c004-f-elisa-presion'}]},
    {id:'c004-n-copia',kind:'analysis',title:'Examinar la copia de Asterión',location:'Laboratorio electrónico',body:'Una lupa revela un empalme a las 23:47. El fragmento procede de una calibración grabada tres noches antes.',imagePublicId:art.scene('laboratorio'),effects:[{effect:'advance_clue',target:'c004-cl-copia-cinta',value:'analyzed'}]},
    {id:'c004-n-fotografia',kind:'analysis',title:'Revelar la exposición de Teresa',location:'Cuarto fotográfico',body:'Los arcos estelares cubren de 00:09:42 a 00:12:18. La sombra de Teresa permanece junto al trípode.',imagePublicId:art.scene('cuarto-fotografico'),effects:[{effect:'advance_clue',target:'c004-cl-larga-exposicion',value:'analyzed'},{effect:'reveal_fact',target:'c004-f-teresa-alibi'}]},
    {id:'c004-n-centralita',kind:'analysis',title:'Escuchar la cinta de la centralita',location:'Sala de comunicaciones',body:'La voz de Soraya consta entre 00:08 y 00:14. Confiesa que llamó a su hermana y falseó la duración.',imagePublicId:art.scene('comunicaciones'),effects:[{effect:'advance_clue',target:'c004-cl-cinta-centralita',value:'analyzed'},{effect:'reveal_fact',target:'c004-f-soraya-alibi'},{effect:'reveal_fact',target:'c004-f-soraya-llamada'}]},
    {id:'c004-n-pluviografo',kind:'analysis',title:'Comprobar la banda meteorológica',location:'Caseta meteorológica',body:'Las notas de Gabriel coinciden con cambios reales a las 00:09, 00:11 y 00:13. La caseta queda demasiado lejos del relé.',imagePublicId:art.scene('comunicaciones'),effects:[{effect:'advance_clue',target:'c004-cl-pluviografo',value:'analyzed'},{effect:'reveal_fact',target:'c004-f-gabriel-alibi'}]},
    {id:'c004-n-gasoil',kind:'analysis',title:'Cuadrar el libro del generador',location:'Cuarto eléctrico',body:'Gabriel admite que vendió cuarenta litros. El registrador prueba que el generador no causó el corte.',imagePublicId:art.scene('cuarto-electrico'),effects:[{effect:'advance_clue',target:'c004-cl-libro-gasoil',value:'analyzed'},{effect:'reveal_fact',target:'c004-f-gabriel-gasoil'}]},
    {id:'c004-n-negativo',kind:'analysis',title:'Revelar el negativo oculto',location:'Cuarto fotográfico',body:'La imagen muestra una partida inflada para la ampliación. Explica el secreto de Teresa, pero fue tomada antes de medianoche.',imagePublicId:art.scene('cuarto-fotografico'),effects:[{effect:'advance_clue',target:'c004-cl-negativo-presupuesto',value:'analyzed'},{effect:'reveal_fact',target:'c004-f-teresa-negativo'}]},
    {id:'c004-n-tunel',kind:'scene',title:'Atravesar el antiguo paso de cables',location:'Bajo la galería',body:'El polvo conserva rodillas y fibras de lana color óxido. Tras el armario de placas, Elisa espera sentada. No está herida. Junto a ella hay revelador, el temporizador sin cable y una bolsa.',imagePublicId:art.scene('tunel'),effects:[{effect:'reveal_fact',target:'c004-f-elisa-desaparecida'},{effect:'discover_clue',target:'c004-cl-cinta-maestra'}]},
    {id:'c004-n-elisa',kind:'interrogation',title:'Tomar declaración a Elisa Montalbán',location:'Cuarto fotográfico',body:'Elisa dice que alguien la golpeó, pero no tiene contusión ni señales de arrastre. Dentro de su bolsa está la cinta maestra; su jersey ha perdido fibras iguales a las del túnel.',imagePublicId:art.scene('elisa'),effects:[{effect:'reveal_fact',target:'c004-f-elisa-cinta'}]},
    {id:'c004-n-maestra',kind:'analysis',title:'Reproducir la cinta maestra',location:'Laboratorio electrónico',body:'Hay ruido hasta las 23:46, una franja desmagnetizada y grabación desde las 23:49. Asterión no existe en el original.',imagePublicId:art.scene('laboratorio'),effects:[{effect:'advance_clue',target:'c004-cl-cinta-maestra',value:'analyzed'}]},
    {id:'c004-n-confrontar-elisa',kind:'interrogation',title:'Confrontar a Elisa con la cinta y el túnel',location:'Cuarto fotográfico',body:'Elisa identifica el empalme como la calibración del miércoles antes de oír su fecha. Tampoco explica sus botas ni cómo el atacante conocía el conducto.',imagePublicId:art.scene('elisa')},
    {id:'c004-n-confrontar-ines',kind:'interrogation',title:'Confrontar a Inés con la llave duplicada',location:'Consola auxiliar',body:'La copia abre el armario, pero no los paneles. El registro mantiene a Inés trabajando durante el corte.',imagePublicId:art.scene('ines')},
    {id:'c004-n-confrontar-soraya',kind:'interrogation',title:'Confrontar a Soraya con la llamada',location:'Sala de comunicaciones',body:'Soraya admite la llamada. La centralita convierte su falta en coartada y confirma que Elisa dictó la única hora no impresa.',imagePublicId:art.scene('soraya')},
    {id:'c004-n-confrontar-teresa',kind:'interrogation',title:'Confrontar a Teresa con el negativo',location:'Cuarto fotográfico',body:'Teresa entrega el negativo y señala el revelador que Elisa le pidió esa tarde. Su exposición la mantiene en la terraza opuesta.',imagePublicId:art.scene('teresa')},
    {id:'c004-n-confrontar-gabriel',kind:'interrogation',title:'Confrontar a Gabriel con el gasóleo',location:'Cuarto eléctrico',body:'Gabriel reconoce la venta. El registrador descarta el generador y sus lecturas lo mantienen lejos del relé.',imagePublicId:art.scene('gabriel')},
    {id:'c004-n-reconstruccion',kind:'analysis',title:'Ordenar los noventa segundos',location:'Sala de control',body:'Una señal sin deriva y empalmada; un relé unido a un temporizador; una falsa caída que conduce a un túnel; una cinta ausente cuando Madrid exigía examinarla.\n\nLas coartadas separan las faltas secundarias del montaje. La acusación final sigue siendo suya.',imagePublicId:art.scene('reconstruccion')},
  ],
  options:[
    ['control','c004-n-control','Examinar la sala de control','Primeras diligencias'],['terraza','c004-n-terraza','Registrar las terrazas','Primeras diligencias'],['antena','c004-n-antena','Inspeccionar la base de la antena','Primeras diligencias'],['electrico','c004-n-electrico','Revisar el cuarto eléctrico','Primeras diligencias'],['archivo','c004-n-archivo','Abrir el archivo técnico','Primeras diligencias'],['despacho','c004-n-despacho','Examinar el despacho de Elisa','Primeras diligencias'],['comunicaciones','c004-n-comunicaciones','Comprobar comunicaciones y meteorología','Primeras diligencias'],['ines','c004-n-ines','Interrogar a Inés Valcárcel','El personal'],['soraya','c004-n-soraya','Interrogar a Soraya Núñez','El personal'],['teresa','c004-n-teresa','Interrogar a Teresa Acedo','El personal'],['gabriel','c004-n-gabriel','Interrogar a Gabriel Requena','El personal'],
  ].map(([id,to,label,line])=>({id:'c004-o-'+id,to,label,line})) as CaseDefinition['options'],
  motives:[
    {id:'c004-mo-prestigio',label:'Ocultar una señal fabricada y conservar la dirección del proyecto'},
    {id:'c004-mo-autoria',label:'Apropiarse de la autoría del receptor antes de marcharse a Bonn'},
    {id:'c004-mo-filtracion',label:'Robar documentos para publicar un escándalo presupuestario'},
    {id:'c004-mo-gasoil',label:'Encubrir el desvío de combustible'},
    {id:'c004-mo-venganza',label:'Desacreditar al equipo tras una disputa profesional'},
  ],
  methods:[
    {id:'c004-me-montaje',label:'Fabricó la señal, temporizó el apagón y fingió una caída para ocultarse con la cinta'},
    {id:'c004-me-generador',label:'Vació el generador y arrojó la cinta al barranco'},
    {id:'c004-me-llave',label:'Usó una llave duplicada durante una avería fortuita'},
    {id:'c004-me-fotografia',label:'Manipuló químicos y escapó por la terraza'},
    {id:'c004-me-radio',label:'Transmitió desde el exterior y secuestró a la directora'},
  ],
  solution:{
    culprit:'c004-s-elisa',motive:'c004-mo-prestigio',method:'c004-me-montaje',
    evidence:['c004-cl-diario-observacion','c004-cl-oscilograma','c004-cl-copia-cinta','c004-cl-rele-proteccion','c004-cl-temporizador','c004-cl-mancha-barandilla','c004-cl-huellas-polvo','c004-cl-plano-conductos','c004-cl-telegrama','c004-cl-cinta-maestra'],
    evidenceGroups:[
      {label:'La señal fue fabricada',importance:'essential',alternatives:[{clueId:'c004-cl-oscilograma',stateKey:'analyzed'},{clueId:'c004-cl-copia-cinta',stateKey:'analyzed'},{clueId:'c004-cl-diario-observacion',stateKey:'analyzed'}]},
      {label:'El apagón fue temporizado',importance:'essential',alternatives:[{clueId:'c004-cl-rele-proteccion',stateKey:'analyzed'},{clueId:'c004-cl-temporizador',stateKey:'analyzed'}]},
      {label:'La caída fue fingida',importance:'essential',alternatives:[{clueId:'c004-cl-mancha-barandilla',stateKey:'analyzed'},{clueId:'c004-cl-huellas-polvo',stateKey:'analyzed'},{clueId:'c004-cl-plano-conductos',stateKey:'analyzed'}]},
      {label:'El móvil y la cinta',importance:'complementary',alternatives:[{clueId:'c004-cl-telegrama',stateKey:'analyzed'},{clueId:'c004-cl-cinta-maestra',stateKey:'analyzed'}]},
    ],
    accusationRequirements:[{requirement:'node',target:'c004-n-tunel'},{requirement:'node',target:'c004-n-elisa'},{requirement:'node',target:'c004-n-ines'},{requirement:'node',target:'c004-n-soraya'},{requirement:'node',target:'c004-n-teresa'},{requirement:'node',target:'c004-n-gabriel'}],
    explanation:'Elisa fabricó Asterión insertando en una copia una calibración anterior. La cinta que Madrid exigía no contenía la señal: examinarla le habría costado la dirección y la financiación.\n\nConectó el relé al temporizador, vertió revelador con óxido en la barandilla y durante el corte entró por el panel al conducto. Se ocultó con la cinta, que pensaba destruir cuando la búsqueda se desplazara al barranco.\n\nLas botas sin tacón, el plano firmado y las fibras fijan su recorrido. Inés ocultaba una llave y su marcha a Bonn, Soraya una llamada, Teresa un negativo y Gabriel el gasóleo vendido. Los registros los sitúan fuera del montaje.',
    epitaph:'Durante noventa segundos apagó el cielo. La cinta conservó la sombra.',
  },
};

const investigations: CaseDefinition['options'] = [
  {id:'registro',to:'c004-n-registro',label:'Interpretar el registro continuo',line:'Comprobaciones',requires:[{requirement:'clue',target:'c004-cl-registro-consola'}]},
  {id:'diario',to:'c004-n-diario',label:'Contrastar el diario con el reloj sidéreo',line:'La señal',requires:[{requirement:'clue',target:'c004-cl-diario-observacion'},{requirement:'fact',target:'c004-f-soraya-diario'}]},
  {id:'oscilograma',to:'c004-n-oscilograma',label:'Medir los pulsos de Asterión',line:'La señal',requires:[{requirement:'clue',target:'c004-cl-oscilograma'},{requirement:'fact',target:'c004-f-ines-pulso'}]},
  {id:'rele',to:'c004-n-rele',label:'Desmontar el relé de protección',line:'El apagón',requires:[{requirement:'clue',target:'c004-cl-rele-proteccion'}]},
  {id:'temporizador',to:'c004-n-temporizador',label:'Comparar el temporizador',line:'El apagón',requires:[{requirement:'clue',target:'c004-cl-temporizador'}]},
  {id:'mancha',to:'c004-n-mancha',label:'Analizar la mancha',line:'La desaparición',requires:[{requirement:'clue',target:'c004-cl-mancha-barandilla'},{requirement:'fact',target:'c004-f-teresa-mancha'}]},
  {id:'huellas',to:'c004-n-huellas',label:'Leer las huellas',line:'La desaparición',requires:[{requirement:'clue',target:'c004-cl-huellas-polvo'},{requirement:'node',target:'c004-n-despacho'}]},
  {id:'plano',to:'c004-n-plano',label:'Reconstruir el conducto de 1968',line:'La desaparición',requires:[{requirement:'clue',target:'c004-cl-plano-conductos'},{requirement:'fact',target:'c004-f-gabriel-tunel'}]},
  {id:'telegrama',to:'c004-n-telegrama',label:'Descifrar el ultimátum de Madrid',line:'El móvil',requires:[{requirement:'clue',target:'c004-cl-telegrama'}]},
  {id:'copia',to:'c004-n-copia',label:'Examinar la copia de Asterión',line:'La señal',requires:[{requirement:'clue',target:'c004-cl-copia-cinta'}]},
  {id:'fotografia',to:'c004-n-fotografia',label:'Revelar la exposición de Teresa',line:'Coartadas',requires:[{requirement:'clue',target:'c004-cl-larga-exposicion'}]},
  {id:'centralita',to:'c004-n-centralita',label:'Escuchar la cinta de la centralita',line:'Coartadas',requires:[{requirement:'clue',target:'c004-cl-cinta-centralita'}]},
  {id:'pluviografo',to:'c004-n-pluviografo',label:'Comprobar el pluviógrafo',line:'Coartadas',requires:[{requirement:'clue',target:'c004-cl-pluviografo'}]},
  {id:'gasoil',to:'c004-n-gasoil',label:'Cuadrar el libro del generador',line:'Comprobaciones',requires:[{requirement:'clue',target:'c004-cl-libro-gasoil'}]},
  {id:'negativo',to:'c004-n-negativo',label:'Revelar el negativo oculto',line:'Comprobaciones',requires:[{requirement:'clue',target:'c004-cl-negativo-presupuesto'}]},
  {id:'tunel',to:'c004-n-tunel',label:'Atravesar el paso de cables',line:'La desaparición',requires:[{requirement:'clue_state',target:'c004-cl-huellas-polvo',value:'analyzed'},{requirement:'clue_state',target:'c004-cl-plano-conductos',value:'analyzed'}]},
  {id:'elisa',to:'c004-n-elisa',label:'Tomar declaración a Elisa Montalbán',line:'El personal',requires:[{requirement:'node',target:'c004-n-tunel'}]},
  {id:'maestra',to:'c004-n-maestra',label:'Reproducir la cinta maestra',line:'La señal',requires:[{requirement:'clue',target:'c004-cl-cinta-maestra'},{requirement:'fact',target:'c004-f-elisa-cinta'}]},
  {id:'confrontar-elisa',to:'c004-n-confrontar-elisa',label:'Confrontar a Elisa con la cinta',line:'Confrontaciones',requires:[{requirement:'clue_state',target:'c004-cl-cinta-maestra',value:'analyzed'},{requirement:'clue_state',target:'c004-cl-copia-cinta',value:'analyzed'}]},
  {id:'confrontar-ines',to:'c004-n-confrontar-ines',label:'Confrontar a Inés con la llave',line:'Confrontaciones',requires:[{requirement:'node',target:'c004-n-registro'},{requirement:'fact',target:'c004-f-ines-llave'}]},
  {id:'confrontar-soraya',to:'c004-n-confrontar-soraya',label:'Confrontar a Soraya con la llamada',line:'Confrontaciones',requires:[{requirement:'clue_state',target:'c004-cl-cinta-centralita',value:'analyzed'}]},
  {id:'confrontar-teresa',to:'c004-n-confrontar-teresa',label:'Confrontar a Teresa con el negativo',line:'Confrontaciones',requires:[{requirement:'clue_state',target:'c004-cl-negativo-presupuesto',value:'analyzed'},{requirement:'clue_state',target:'c004-cl-larga-exposicion',value:'analyzed'}]},
  {id:'confrontar-gabriel',to:'c004-n-confrontar-gabriel',label:'Confrontar a Gabriel con el gasóleo',line:'Confrontaciones',requires:[{requirement:'clue_state',target:'c004-cl-libro-gasoil',value:'analyzed'},{requirement:'clue_state',target:'c004-cl-pluviografo',value:'analyzed'}]},
  {id:'reconstruccion',to:'c004-n-reconstruccion',label:'Ordenar los noventa segundos',line:'Conclusiones',requires:[{requirement:'node',target:'c004-n-oscilograma'},{requirement:'node',target:'c004-n-rele'},{requirement:'node',target:'c004-n-tunel'},{requirement:'node',target:'c004-n-maestra'},{requirement:'node',target:'c004-n-telegrama'}]},
].map(option=>({...option,id:'c004-o-'+option.id})) as CaseDefinition['options'];

case004.options.push(...investigations);
